---
- hosts: 172.31.29.172
  become: yes
  tasks:
  - name: execute direct linux command
    command: hostname -f
    register: myresult

  - name: i want to display my first task result 
    debug: 
       msg: "{{myresult}}"

  - name: install tree
    apt:
       name: tree
       state: present
    when: myresult.stderr !=""

  - name: install wget 
    apt:
       name: wget
       state: present
    when: myresult.stderr ==""