---
- hosts: 172.31.29.172
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy text file into node side
    copy:
       src: mytest
       dest: /home/maha/mytest
  - name: install apache2 webserver 
    apt:
      name: apache2
      state: present
