---
- hosts: myWebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 on ubuntu nodes
    apt:
      name: "{{mywebpackonubuntu}}" 
      state: present
    when: ansible_os_family == "Debian"
    
  - name: i want to start apache2 service 
    service:
        name: "{{mywebpackonubuntu}}" 
        state: started
    when: ansible_os_family == "Debian"

  - name: install httpd on redhat nodes
    dnf:
        name: "{{mywebpackonredhat}}"
        state: present
    when: ansible_os_family == "RedHat"

  - name: i want to start httpd service
    service:
        name: "{{mywebpackonredhat}}"
        state: started 
    when: ansible_os_family == "RedHat"