---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 on ubuntu nodes
    apt:
      name: apache2 
      state: present
    
  - name: i want to start apache2 service 
    service:
        name: apache2 
        state: started

