#SPDX-License-Identifier: MIT-0
---
# tasks file for mytomcatrole
- include_tasks: installjava.yml
- include_tasks: downloadtomcat.yml
- include_tasks: usergroup.yml
- include_tasks: permission.yml
- include_tasks: tomcatservice.yml
- include_tasks: starttomcat.yml